name: "Install Node environment"
description: "Install Node environment reading packages from cache if available"

runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn

    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v3
      with:
        path: "~/.cache"
        key: cypress-binary-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      run: yarn install --immutable --immutable-cache
      shell: bash
