name: "Install Node environment"
description: "Install Node environment reading packages from cache if available"

runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '.nvmrc'
        cache: yarn

    - name: Cache node_modules
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v3
      with:
        path: "~/.cache"
        key: cypress-binary-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
      run: yarn install --immutable --immutable-cache
      shell: bash
