/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import type {
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface WhitelistInterface extends utils.Interface {
  functions: {
    "addressBook()": FunctionFragment;
    "blacklistCallee(address)": FunctionFragment;
    "blacklistCollateral(address)": FunctionFragment;
    "blacklistOtoken(address)": FunctionFragment;
    "blacklistProduct(address,address,address,bool)": FunctionFragment;
    "isWhitelistedCallee(address)": FunctionFragment;
    "isWhitelistedCollateral(address)": FunctionFragment;
    "isWhitelistedOtoken(address)": FunctionFragment;
    "isWhitelistedProduct(address,address,address,bool)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistCallee(address)": FunctionFragment;
    "whitelistCollateral(address)": FunctionFragment;
    "whitelistOtoken(address)": FunctionFragment;
    "whitelistProduct(address,address,address,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addressBook"
      | "blacklistCallee"
      | "blacklistCollateral"
      | "blacklistOtoken"
      | "blacklistProduct"
      | "isWhitelistedCallee"
      | "isWhitelistedCollateral"
      | "isWhitelistedOtoken"
      | "isWhitelistedProduct"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "whitelistCallee"
      | "whitelistCollateral"
      | "whitelistOtoken"
      | "whitelistProduct"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addressBook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistCallee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistCollateral",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistOtoken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistProduct",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedCallee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedCollateral",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedOtoken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedProduct",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistCallee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistCollateral",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistOtoken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistProduct",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistCallee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistOtoken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedCallee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedOtoken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistCallee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistOtoken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistProduct",
    data: BytesLike
  ): Result;

  events: {
    "CalleeBlacklisted(address)": EventFragment;
    "CalleeWhitelisted(address)": EventFragment;
    "CollateralBlacklisted(address)": EventFragment;
    "CollateralWhitelisted(address)": EventFragment;
    "OtokenBlacklisted(address)": EventFragment;
    "OtokenWhitelisted(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProductBlacklisted(bytes32,address,address,address,bool)": EventFragment;
    "ProductWhitelisted(bytes32,address,address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CalleeBlacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CalleeWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollateralBlacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollateralWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OtokenBlacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OtokenWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductBlacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductWhitelisted"): EventFragment;
}

export interface CalleeBlacklistedEventObject {
  _callee: string;
}
export type CalleeBlacklistedEvent = TypedEvent<
  [string],
  CalleeBlacklistedEventObject
>;

export type CalleeBlacklistedEventFilter =
  TypedEventFilter<CalleeBlacklistedEvent>;

export interface CalleeWhitelistedEventObject {
  _callee: string;
}
export type CalleeWhitelistedEvent = TypedEvent<
  [string],
  CalleeWhitelistedEventObject
>;

export type CalleeWhitelistedEventFilter =
  TypedEventFilter<CalleeWhitelistedEvent>;

export interface CollateralBlacklistedEventObject {
  collateral: string;
}
export type CollateralBlacklistedEvent = TypedEvent<
  [string],
  CollateralBlacklistedEventObject
>;

export type CollateralBlacklistedEventFilter =
  TypedEventFilter<CollateralBlacklistedEvent>;

export interface CollateralWhitelistedEventObject {
  collateral: string;
}
export type CollateralWhitelistedEvent = TypedEvent<
  [string],
  CollateralWhitelistedEventObject
>;

export type CollateralWhitelistedEventFilter =
  TypedEventFilter<CollateralWhitelistedEvent>;

export interface OtokenBlacklistedEventObject {
  otoken: string;
}
export type OtokenBlacklistedEvent = TypedEvent<
  [string],
  OtokenBlacklistedEventObject
>;

export type OtokenBlacklistedEventFilter =
  TypedEventFilter<OtokenBlacklistedEvent>;

export interface OtokenWhitelistedEventObject {
  otoken: string;
}
export type OtokenWhitelistedEvent = TypedEvent<
  [string],
  OtokenWhitelistedEventObject
>;

export type OtokenWhitelistedEventFilter =
  TypedEventFilter<OtokenWhitelistedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ProductBlacklistedEventObject {
  productHash: string;
  underlying: string;
  strike: string;
  collateral: string;
  isPut: boolean;
}
export type ProductBlacklistedEvent = TypedEvent<
  [string, string, string, string, boolean],
  ProductBlacklistedEventObject
>;

export type ProductBlacklistedEventFilter =
  TypedEventFilter<ProductBlacklistedEvent>;

export interface ProductWhitelistedEventObject {
  productHash: string;
  underlying: string;
  strike: string;
  collateral: string;
  isPut: boolean;
}
export type ProductWhitelistedEvent = TypedEvent<
  [string, string, string, string, boolean],
  ProductWhitelistedEventObject
>;

export type ProductWhitelistedEventFilter =
  TypedEventFilter<ProductWhitelistedEvent>;

export interface Whitelist extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WhitelistInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addressBook(overrides?: CallOverrides): Promise<[string]>;

    blacklistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blacklistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blacklistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blacklistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isWhitelistedCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelistedCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelistedOtoken(
      _otoken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelistedProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addressBook(overrides?: CallOverrides): Promise<string>;

  blacklistCallee(
    _callee: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blacklistCollateral(
    _collateral: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blacklistOtoken(
    _otokenAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blacklistProduct(
    _underlying: PromiseOrValue<string>,
    _strike: PromiseOrValue<string>,
    _collateral: PromiseOrValue<string>,
    _isPut: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isWhitelistedCallee(
    _callee: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhitelistedCollateral(
    _collateral: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhitelistedOtoken(
    _otoken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhitelistedProduct(
    _underlying: PromiseOrValue<string>,
    _strike: PromiseOrValue<string>,
    _collateral: PromiseOrValue<string>,
    _isPut: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistCallee(
    _callee: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistCollateral(
    _collateral: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistOtoken(
    _otokenAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistProduct(
    _underlying: PromiseOrValue<string>,
    _strike: PromiseOrValue<string>,
    _collateral: PromiseOrValue<string>,
    _isPut: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addressBook(overrides?: CallOverrides): Promise<string>;

    blacklistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    blacklistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    blacklistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    blacklistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    isWhitelistedCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhitelistedCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhitelistedOtoken(
      _otoken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhitelistedProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CalleeBlacklisted(address)"(
      _callee?: PromiseOrValue<string> | null
    ): CalleeBlacklistedEventFilter;
    CalleeBlacklisted(
      _callee?: PromiseOrValue<string> | null
    ): CalleeBlacklistedEventFilter;

    "CalleeWhitelisted(address)"(
      _callee?: PromiseOrValue<string> | null
    ): CalleeWhitelistedEventFilter;
    CalleeWhitelisted(
      _callee?: PromiseOrValue<string> | null
    ): CalleeWhitelistedEventFilter;

    "CollateralBlacklisted(address)"(
      collateral?: PromiseOrValue<string> | null
    ): CollateralBlacklistedEventFilter;
    CollateralBlacklisted(
      collateral?: PromiseOrValue<string> | null
    ): CollateralBlacklistedEventFilter;

    "CollateralWhitelisted(address)"(
      collateral?: PromiseOrValue<string> | null
    ): CollateralWhitelistedEventFilter;
    CollateralWhitelisted(
      collateral?: PromiseOrValue<string> | null
    ): CollateralWhitelistedEventFilter;

    "OtokenBlacklisted(address)"(
      otoken?: PromiseOrValue<string> | null
    ): OtokenBlacklistedEventFilter;
    OtokenBlacklisted(
      otoken?: PromiseOrValue<string> | null
    ): OtokenBlacklistedEventFilter;

    "OtokenWhitelisted(address)"(
      otoken?: PromiseOrValue<string> | null
    ): OtokenWhitelistedEventFilter;
    OtokenWhitelisted(
      otoken?: PromiseOrValue<string> | null
    ): OtokenWhitelistedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "ProductBlacklisted(bytes32,address,address,address,bool)"(
      productHash?: null,
      underlying?: PromiseOrValue<string> | null,
      strike?: PromiseOrValue<string> | null,
      collateral?: PromiseOrValue<string> | null,
      isPut?: null
    ): ProductBlacklistedEventFilter;
    ProductBlacklisted(
      productHash?: null,
      underlying?: PromiseOrValue<string> | null,
      strike?: PromiseOrValue<string> | null,
      collateral?: PromiseOrValue<string> | null,
      isPut?: null
    ): ProductBlacklistedEventFilter;

    "ProductWhitelisted(bytes32,address,address,address,bool)"(
      productHash?: null,
      underlying?: PromiseOrValue<string> | null,
      strike?: PromiseOrValue<string> | null,
      collateral?: PromiseOrValue<string> | null,
      isPut?: null
    ): ProductWhitelistedEventFilter;
    ProductWhitelisted(
      productHash?: null,
      underlying?: PromiseOrValue<string> | null,
      strike?: PromiseOrValue<string> | null,
      collateral?: PromiseOrValue<string> | null,
      isPut?: null
    ): ProductWhitelistedEventFilter;
  };

  estimateGas: {
    addressBook(overrides?: CallOverrides): Promise<BigNumber>;

    blacklistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blacklistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blacklistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blacklistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isWhitelistedCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelistedCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelistedOtoken(
      _otoken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelistedProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressBook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blacklistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blacklistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blacklistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blacklistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isWhitelistedCallee(
      _callee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelistedCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelistedOtoken(
      _otoken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelistedProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistCallee(
      _callee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistCollateral(
      _collateral: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistOtoken(
      _otokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistProduct(
      _underlying: PromiseOrValue<string>,
      _strike: PromiseOrValue<string>,
      _collateral: PromiseOrValue<string>,
      _isPut: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
