/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MockOpynFactoryInterface extends utils.Interface {
  functions: {
    "OTOKEN_DECIMALS()": FunctionFragment;
    "getOtoken(address,address,address,uint256,uint256,bool)": FunctionFragment;
    "getTargetOtokenAddress(address,address,address,uint256,uint256,bool)": FunctionFragment;
    "otoken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "OTOKEN_DECIMALS"
      | "getOtoken"
      | "getTargetOtokenAddress"
      | "otoken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "OTOKEN_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOtoken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetOtokenAddress",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: "otoken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "OTOKEN_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOtoken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTargetOtokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "otoken", data: BytesLike): Result;

  events: {};
}

export interface MockOpynFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockOpynFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    OTOKEN_DECIMALS(overrides?: CallOverrides): Promise<[number]>;

    getOtoken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTargetOtokenAddress(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    otoken(overrides?: CallOverrides): Promise<[string]>;
  };

  OTOKEN_DECIMALS(overrides?: CallOverrides): Promise<number>;

  getOtoken(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<string>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BigNumberish>,
    arg5: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTargetOtokenAddress(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<string>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BigNumberish>,
    arg5: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<string>;

  otoken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    OTOKEN_DECIMALS(overrides?: CallOverrides): Promise<number>;

    getOtoken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTargetOtokenAddress(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    otoken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    OTOKEN_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    getOtoken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTargetOtokenAddress(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    otoken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    OTOKEN_DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOtoken(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTargetOtokenAddress(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BigNumberish>,
      arg5: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    otoken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
