# Builds potion-dapp project in test mode and runs testing

on:
  workflow_call:
    secrets:
      VITE_DEVELOPMENT_MNEMONIC:
        required: true
      VITE_ALCHEMY_KEY:
        required: true
      VITE_DEVELOPMENT_ADDRESS:
        required: true
      VITE_SUBGRAPH_ADDRESS:
        required: true
      VITE_BLOCKNATIVE_API_KEY:
        required: true
      DEPLOYER_MNEMONIC:
        required: true
      GANACHE_VOLUME:
        required: true
      DATABASE_PATH:
        required: true
    inputs:
      VITE_ETHEREUM_NETWORK:
        required: true
        type: string
      VITE_ENDPOINT_PROVIDER:
        required: true
        type: string
      VITE_COINGECKO_API_ENDPOINT:
        required: true
        type: string

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Nx linting
        run: yarn lint-all

  run-unit-test-contracts:
    name: Run unit tests (contracts)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Contracts unit test
        run: yarn nx run potion-contracts:test
        env:
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          VITE_ENDPOINT_PROVIDER: ${{ inputs.VITE_ENDPOINT_PROVIDER }}
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}

  run-unit-test-dapp:
    name: Run unit tests (dapp)
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      VITE_ETHEREUM_NETWORK: ${{ inputs.VITE_ETHEREUM_NETWORK }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Codegen
        run: yarn codegen subgraph-queries

      - name: Dapp unit test
        run: yarn nx run potion-dapp:test-unit

      - name: Dapp test report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Vitest Tests
          path: apps/potion-dapp/reports/report.xml
          reporter: jest-junit

  run-unit-test-subgraph:
    name: Run unit tests (subgraph)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Prepare subgraph.yaml
        run: yarn nx run potion-subgraph:prepare-local

      - name: Codegen
        run: yarn codegen potion-subgraph

      - name: Subgraph unit test
        run: yarn test-unit potion-subgraph

      - name: Subgraph coverage
        if: success()
        run: yarn nx run potion-subgraph:coverage

  run-component-tests:
    name: Run component tests
    runs-on: ubuntu-latest
    needs: [run-unit-test-dapp]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Cypress run (potion-ui components)
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: chrome
          record: false
          component: true
          working-directory: libs/potion-ui

      - name: Archive screenshots code coverage results (potion-ui components)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: potion-ui-components-cypress-screenshots
          path: libs/potion-ui/cypress/screenshots
          retention-days: 25

      - name: Archive videos code coverage results (potion-ui components)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: potion-ui-components-cypress-videos
          path: libs/potion-ui/cypress/videos
          retention-days: 25

  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    needs: [run-component-tests, run-unit-test-subgraph, run-unit-test-contracts]
    env:
      PREVIEW_URL: "http://127.0.0.1:5050"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Copy seeds in the Ganache volume
        run: bin/setup-database-seed --all
        shell: bash
        env:
          GANACHE_VOLUME: ${{ secrets.GANACHE_VOLUME }}

      - name: Create and seed environment
        run: ./bin/setup-local-env
        shell: bash
        env:
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          GANACHE_VOLUME: ${{ secrets.GANACHE_VOLUME }}
          DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
          CHAIN_TIME: ${{ secrets.CREATE_CHAIN_TIME }}
          VITE_DEVELOPMENT_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
          VITE_DEVELOPMENT_ADDRESS: ${{ secrets.VITE_DEVELOPMENT_ADDRESS }}
          VITE_SUBGRAPH_ADDRESS: ${{ secrets.VITE_SUBGRAPH_ADDRESS }}
          VITE_ETHEREUM_NETWORK: ${{ inputs.VITE_ETHEREUM_NETWORK }}
          VITE_ENDPOINT_PROVIDER: ${{ inputs.VITE_ENDPOINT_PROVIDER }}
          VITE_COINGECKO_API_ENDPOINT: ${{ inputs.VITE_COINGECKO_API_ENDPOINT }}
          VITE_BLOCKNATIVE_API_KEY: ${{ inputs.VITE_BLOCKNATIVE_API_KEY }}

      - name: Build app with mocked onboard
        run: yarn nx run potion-dapp:build-test
        env:
          VITE_DEVELOPMENT_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
          VITE_DEVELOPMENT_ADDRESS: ${{ secrets.VITE_DEVELOPMENT_ADDRESS }}
          VITE_SUBGRAPH_ADDRESS: ${{ secrets.VITE_SUBGRAPH_ADDRESS }}
          VITE_ETHEREUM_NETWORK: ${{ inputs.VITE_ETHEREUM_NETWORK }}
          VITE_ENDPOINT_PROVIDER: ${{ inputs.VITE_ENDPOINT_PROVIDER }}
          VITE_COINGECKO_API_ENDPOINT: ${{ inputs.VITE_COINGECKO_API_ENDPOINT }}
          VITE_BLOCKNATIVE_API_KEY: ${{ inputs.VITE_BLOCKNATIVE_API_KEY }}

      - name: Cypress run (potion-dapp e2e)
        uses: cypress-io/github-action@v4
        env:
          GANACHE_VOLUME: ${{ secrets.GANACHE_VOLUME }}
          CHAIN_TIME: ${{ secrets.CHAIN_TIME }}
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
        with:
          install: false
          start: yarn preview
          wait-on: ${{ env.PREVIEW_URL }}
          browser: chrome
          record: false
          working-directory: apps/potion-dapp
          config: "pageLoadTimeout=100000,baseUrl=${{ env.PREVIEW_URL }}"

      - name: Archive screenshots code coverage results (potion-dapp e2e)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: potion-dapp-e2e-cypress-screenshots
          path: apps/potion-dapp/cypress/screenshots
          retention-days: 25

      - name: Archive videos code coverage results (potion-dapp e2e)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: potion-dapp-e2e-cypress-videos
          path: apps/potion-dapp/cypress/videos
          retention-days: 25

      - name: Setup tmate session to debug errors
        # if: ${{ failure() }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

